// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR2mY1g6Qrs85Lxry6yypYfeTIB1aD1IE',
    appId: '1:365577860639:web:836346b3231d4de293072a',
    messagingSenderId: '365577860639',
    projectId: 'mood-diary-auth-b525b',
    authDomain: 'mood-diary-auth-b525b.firebaseapp.com',
    storageBucket: 'mood-diary-auth-b525b.firebasestorage.app',
    measurementId: 'G-XM42C6KHJ1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR2mY1g6Qrs85Lxry6yypYfeTIB1aD1IE',
    appId: '1:365577860639:web:cc2c466fb2d5ef1793072a',
    messagingSenderId: '365577860639',
    projectId: 'mood-diary-auth-b525b',
    authDomain: 'mood-diary-auth-b525b.firebaseapp.com',
    storageBucket: 'mood-diary-auth-b525b.firebasestorage.app',
    measurementId: 'G-BX6NC5315M',
  );
}
